## Task B

In [180]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from collections import Counter

__1. Using the image labels as the independent variables __

In [173]:
len(normalized_data.iloc[:, 4])

794

__Get all the features__

In [163]:
labels_list = []
for row in normalized_data.iloc[:, 4]:
    for label in row:
        labels_list.append(label)
len(labels_list)

6774

In [168]:
cnt =Counter(labels_list)
cntlabel = cnt.most_common(None)
labels=[]
for i in cntlabel:
    labels.append(i[0])
len(labels)

1081

In [187]:
labels[0]

'sky'

__get a list of label dictionary shows the number of each label occured in each post__

In [202]:
worddict={}
worddict_list = []
for i in range(0,len(normalized_data)):
    worddict = dict.fromkeys(labels, 0) 
    worddict_list.append(worddict)
len(worddict_list)    

794

In [203]:
worddict_list[0]

{'sky': 0,
 'wildlife': 0,
 'fauna': 0,
 'water': 0,
 'tree': 0,
 'organism': 0,
 'mammal': 0,
 'terrestrial animal': 0,
 'girl': 0,
 'fun': 0,
 'wilderness': 0,
 'snout': 0,
 'recreation': 0,
 'sea': 0,
 'ecosystem': 0,
 'grass': 0,
 'mountain': 0,
 'cloud': 0,
 'landscape': 0,
 'rock': 0,
 'atmosphere': 0,
 'plant': 0,
 'temple': 0,
 'horizon': 0,
 'darkness': 0,
 'geological phenomenon': 0,
 'highland': 0,
 'nature': 0,
 'ecoregion': 0,
 'reflection': 0,
 'bird': 0,
 'grassland': 0,
 'night': 0,
 'morning': 0,
 'beak': 0,
 'mountainous landforms': 0,
 'ocean': 0,
 'vacation': 0,
 'marine biology': 0,
 'geology': 0,
 'sand': 0,
 'national park': 0,
 'tradition': 0,
 'city': 0,
 'whiskers': 0,
 'formation': 0,
 'close up': 0,
 'big cats': 0,
 'tourism': 0,
 'nature reserve': 0,
 'vehicle': 0,
 'carnivoran': 0,
 'human': 0,
 'arctic': 0,
 'marine mammal': 0,
 'terrain': 0,
 'ridge': 0,
 'calm': 0,
 'wood': 0,
 'fur': 0,
 'hill': 0,
 'vegetation': 0,
 'computer wallpaper': 0,
 'mountain

In [207]:
for i in range(0,len(worddict_list)):
    for word in normalized_data.iloc[i, 4] :
        worddict_list[i][word] =1
len(worddict_list)

794

In [235]:
worddict_list[0] # for the first post, show the total number of each label in the post

{'sky': 0,
 'wildlife': 0,
 'fauna': 0,
 'water': 0,
 'tree': 1,
 'organism': 0,
 'mammal': 0,
 'terrestrial animal': 0,
 'girl': 0,
 'fun': 0,
 'wilderness': 0,
 'snout': 0,
 'recreation': 1,
 'sea': 0,
 'ecosystem': 0,
 'grass': 0,
 'mountain': 0,
 'cloud': 0,
 'landscape': 0,
 'rock': 0,
 'atmosphere': 0,
 'plant': 0,
 'temple': 1,
 'horizon': 0,
 'darkness': 0,
 'geological phenomenon': 0,
 'highland': 0,
 'nature': 0,
 'ecoregion': 0,
 'reflection': 0,
 'bird': 0,
 'grassland': 0,
 'night': 0,
 'morning': 0,
 'beak': 0,
 'mountainous landforms': 0,
 'ocean': 0,
 'vacation': 0,
 'marine biology': 0,
 'geology': 0,
 'sand': 0,
 'national park': 0,
 'tradition': 0,
 'city': 0,
 'whiskers': 0,
 'formation': 0,
 'close up': 0,
 'big cats': 0,
 'tourism': 0,
 'nature reserve': 0,
 'vehicle': 0,
 'carnivoran': 0,
 'human': 0,
 'arctic': 0,
 'marine mammal': 0,
 'terrain': 0,
 'ridge': 0,
 'calm': 0,
 'wood': 0,
 'fur': 0,
 'hill': 0,
 'vegetation': 0,
 'computer wallpaper': 0,
 'mountain

__Turn to the dataframe__

In [213]:
df1 = pd.DataFrame(worddict_list)

__Functions to compute TF-IDF score__

In [192]:
def computeTF(wordDict, bow):
    tfDict = {}
    bowCount = len(bow)
    for word, count in wordDict.items():
        tfDict[word] = count/float(bowCount)
    return tfDict

def computeIDF(docList):
    import math
    idfDict = {}
    N = len(docList)
    
    idfDict = dict.fromkeys(docList[0].keys(), 0)
    for doc in docList:
        for word, val in doc.items():
            if val > 0:
                idfDict[word] += 1
    
    for word, val in idfDict.items():
        idfDict[word] = math.log10(N / float(val))
        
    return idfDict

def computeTFIDF(tfBow, idfs):
    tfidf = {}
    for word, val in tfBow.items():
        tfidf[word] = val*idfs[word]
    return tfidf

In [214]:
# tf score of labels in each post
tf = []
for i in range(0,len(normalized_data)):
    tf.append(computeTF(df1.iloc[i], normalized_data.iloc[i, 4]))
tf[2]

{'abdomen': 0.0,
 'academic dress': 0.0,
 'accipitriformes': 0.0,
 'acrylic paint': 0.0,
 'adventure': 0.0,
 'advertising': 0.0,
 'aeolian landform': 0.0,
 'aerial photography': 0.0,
 'aerospace engineering': 0.0,
 'african elephant': 0.0,
 'afterglow': 0.0,
 'agaricomycetes': 0.0,
 'agricultural machinery': 0.0,
 'agriculture': 0.0,
 'air force': 0.0,
 'air sports': 0.0,
 'air travel': 0.0,
 'aircraft': 0.0,
 'aircraft engine': 0.0,
 'airplane': 0.0,
 'alaunt': 0.0,
 'albatross': 0.0,
 'album cover': 0.0,
 'algae': 0.0,
 'alley': 0.0,
 'alligator': 0.0,
 'alps': 0.0,
 'american alligator': 0.0,
 'american black bear': 0.0,
 'amphibian': 0.0,
 'ancient history': 0.0,
 'ancient roman architecture': 0.0,
 'ancient rome': 0.0,
 'anemone fish': 0.0,
 'angle': 0.0,
 'angling': 0.0,
 'animal figure': 0.0,
 'animal migration': 0.0,
 'animal source foods': 0.0,
 'ant': 0.0,
 'antelope': 0.0,
 'apartment': 0.0,
 'aqua': 0.0,
 'arabian camel': 0.0,
 'arcade': 0.0,
 'arch': 0.0,
 'archaeological 

In [216]:
# idf score of each label
idf = computeIDF(worddict_list)
idf

{'sky': 0.536208522534952,
 'wildlife': 0.7354676466426592,
 'fauna': 0.7727157040622886,
 'water': 0.8206392563794714,
 'tree': 0.8506024797569146,
 'organism': 0.8912203306651787,
 'mammal': 0.9313375538731611,
 'terrestrial animal': 0.9967305154351527,
 'girl': 1.0133297772546144,
 'fun': 1.03058878269612,
 'wilderness': 1.0802765668852277,
 'snout': 1.0936405284432091,
 'recreation': 1.1004799529735145,
 'sea': 1.1074288129288423,
 'ecosystem': 1.1216692520434526,
 'grass': 1.1439456467546048,
 'mountain': 1.1516324754208958,
 'cloud': 1.1838171587922972,
 'landscape': 1.19225032632916,
 'rock': 1.19225032632916,
 'atmosphere': 1.218579265051509,
 'plant': 1.227722644491379,
 'temple': 1.2563678259409088,
 'horizon': 1.2466079886517527,
 'darkness': 1.2563678259409088,
 'geological phenomenon': 1.2765712120291959,
 'highland': 1.2870366457073608,
 'nature': 1.320036905810286,
 'ecoregion': 1.3316187783601012,
 'reflection': 1.343518001659809,
 'bird': 1.343518001659809,
 'grassland

In [217]:
#tfidf score
tfidf = []
for i in range(0,len(normalized_data)):
    tfidf.append(computeTFIDF(tf[i], idf))
tfidf[0]

{'abdomen': 0.0,
 'academic dress': 0.0,
 'accipitriformes': 0.0,
 'acrylic paint': 0.0,
 'adventure': 0.0,
 'advertising': 0.0,
 'aeolian landform': 0.0,
 'aerial photography': 0.0,
 'aerospace engineering': 0.0,
 'african elephant': 0.0,
 'afterglow': 0.0,
 'agaricomycetes': 0.0,
 'agricultural machinery': 0.0,
 'agriculture': 0.0,
 'air force': 0.0,
 'air sports': 0.0,
 'air travel': 0.0,
 'aircraft': 0.0,
 'aircraft engine': 0.0,
 'airplane': 0.0,
 'alaunt': 0.0,
 'albatross': 0.0,
 'album cover': 0.0,
 'algae': 0.0,
 'alley': 0.0,
 'alligator': 0.0,
 'alps': 0.0,
 'american alligator': 0.0,
 'american black bear': 0.0,
 'amphibian': 0.0,
 'ancient history': 0.0,
 'ancient roman architecture': 0.0,
 'ancient rome': 0.0,
 'anemone fish': 0.0,
 'angle': 0.0,
 'angling': 0.0,
 'animal figure': 0.0,
 'animal migration': 0.0,
 'animal source foods': 0.0,
 'ant': 0.0,
 'antelope': 0.0,
 'apartment': 0.0,
 'aqua': 0.0,
 'arabian camel': 0.0,
 'arcade': 0.0,
 'arch': 0.0,
 'archaeological 

__Turn to the dataframe__

In [220]:
tfidf_df = pd.DataFrame(tfidf)
# tfidf_df

__Run a logistic regression__

In [221]:
lr1 = LogisticRegression()
lr1.fit(tfidf_df.iloc[:], normalized_data.iloc[:,-1])
pred1 = lr1.predict(tfidf_df.iloc[:])
matrix1 = confusion_matrix(normalized_data.iloc[:,-1], pred1)
matrix1

array([[304,  86],
       [ 40, 364]])

In [222]:
confusion_matrix_chart1 = pd.DataFrame(matrix1, columns=["Actual: True", "Actual: False"],  index=["Predicted: True", "Predicted: False"])
confusion_matrix_chart1

Actual: True  Actual: False
Predicted: True            304             86
Predicted: False            40            364

In [223]:
Accuracy = (304+364)/(304+86+40+364)
Accuracy

0.8413098236775819

__2. Using the post caption words as the independent variables instead of image labels__

In [110]:
from nltk.corpus import stopwords
from nltk.corpus import brown
from nltk.tokenize import word_tokenize,sent_tokenize
from string import punctuation, digits
from collections import Counter
stopwords_set = set(stopwords.words('english'))
brown_set = set(brown.words())
characterstoclean = r'?!,:,/\"-+=@#$%^&*()><{}[]|' + r"'"
punc = punctuation

In [73]:
description=list(map(lambda x: x.lower(), normalized_data.iloc[:,1]))
len(description)

794

In [126]:
description[0]

'photo by @amivitale | ntipiyon nonguta and her son bernard, one, relax with their neighbors as they make beaded belts for theloisaba community trust in ewaso village in laikipia, kenya. these women are in a community surrounding loisaba conservancy (@loisaba_conservancy) and are being supported and given access to international markets. revenue from ecotourism is reinvested into neighboring communities like #ewaso.\n\nto get involved and learn more about community based conservation, please follow @loisaba_conservancy and @amivitale.\n\n@nature_org @natgeoimagecollection #kenya #magicalkenya #whyilovekenya #northernkenya #africa #children #mothersandsons #mothers #empowerment #conservation #everydayafrica #photojournalism #amivitale'

In [131]:
row = str()
des_list = []
for des in description :
    for word in word_tokenize(des):
         if word in brown_set  and word not in stopwords_set and word not in characterstoclean and word not in punc and not word.isdigit() and word.isalpha():
                row = row +' '+word
    des_list.append(row)
len(des_list)

794

In [132]:
des_list[0]

' photo son one relax neighbors make beaded belts community trust village women community surrounding supported given access international markets revenue neighboring communities like get involved learn community based conservation please follow children mothers conservation'

__Get TF-IDF score of each word in each post__

In [133]:
tfidf_vec = TfidfVectorizer()
tfidf_matrix = tfidf_vec.fit_transform(des_list)

# get all the features 得到语料库所有不重复的词
print(tfidf_vec.get_feature_names())


['abandoned', 'abhorrent', 'abides', 'abilities', 'ability', 'able', 'abode', 'aboriginal', 'aborigines', 'abroad', 'absence', 'absent', 'absolute', 'absolutely', 'absorb', 'absorbing', 'abstract', 'absurd', 'abundance', 'abundant', 'abuse', 'abused', 'abuses', 'abyss', 'acacia', 'academy', 'accent', 'accept', 'acceptance', 'accepted', 'accepting', 'accepts', 'access', 'accessible', 'accidentally', 'accommodate', 'accommodation', 'accompanied', 'accompanying', 'accomplished', 'accord', 'according', 'account', 'accounts', 'achieve', 'achieved', 'achievement', 'achievements', 'acknowledge', 'acknowledges', 'acquaint', 'acre', 'acres', 'acrobatic', 'across', 'act', 'action', 'actions', 'activated', 'active', 'actively', 'activities', 'activity', 'actors', 'actual', 'actually', 'ad', 'adapt', 'adaptable', 'adaptation', 'adapted', 'add', 'added', 'addicted', 'addiction', 'addicts', 'adding', 'addition', 'address', 'addressed', 'adds', 'adequately', 'adhere', 'adjacent', 'administration', 'a

In [134]:
# # 得到每个单词对应的id值
print(tfidf_vec.vocabulary_)

{'photo': 4638, 'son': 6013, 'one': 4343, 'relax': 5233, 'neighbors': 4205, 'make': 3817, 'beaded': 484, 'belts': 543, 'community': 1204, 'trust': 6782, 'village': 6981, 'women': 7198, 'surrounding': 6368, 'supported': 6347, 'given': 2801, 'access': 32, 'international': 3403, 'markets': 3863, 'revenue': 5405, 'neighboring': 4204, 'communities': 1203, 'like': 3673, 'get': 2785, 'involved': 3439, 'learn': 3617, 'based': 465, 'conservation': 1284, 'please': 4737, 'follow': 2596, 'children': 1019, 'mothers': 4097, 'photos': 4647, 'world': 7218, 'remaining': 5253, 'fir': 2511, 'trees': 6743, 'create': 1444, 'dense': 1644, 'cover': 1415, 'forest': 2623, 'approximately': 274, 'percent': 4589, 'covered': 1417, 'forests': 2625, 'country': 1398, 'government': 2846, 'mandate': 3837, 'protected': 4976, 'time': 6598, 'despite': 1689, 'environmental': 2150, 'commitment': 1189, 'glaciers': 2805, 'retreating': 5390, 'melting': 3933, 'causing': 917, 'dangerous': 1544, 'floods': 2563, 'resource': 5349, 

In [137]:
# get the TF-IDF score of each word of each post according to id of the words
print(tfidf_matrix.toarray())

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.00719109 0.00179679 0.00104124 ... 0.00270196 0.0081674  0.00125032]
 [0.00718874 0.0017962  0.0010409  ... 0.00270107 0.00816473 0.00124991]
 [0.00716406 0.00179004 0.00103733 ... 0.0026918  0.0081367  0.00124562]]


__Run a logistic regression__

In [145]:
lr2 = LogisticRegression()
lr2.fit(tfidf_matrix, normalized_data.iloc[:,-1])
pred2 = lr2.predict(tfidf_matrix)
matrix2 = confusion_matrix(normalized_data.iloc[:,-1], pred2)
matrix2

array([[154, 236],
       [118, 286]])

In [146]:
confusion_matrix_chart2 = pd.DataFrame(matrix2, columns=["Actual: True", "Actual: False"],  index=["Predicted: True", "Predicted: False"])
confusion_matrix_chart2

Actual: True  Actual: False
Predicted: True            154            236
Predicted: False           118            286

In [147]:
Accuracy2 = (154+286)/(154+236+118+286)
Accuracy2

0.5541561712846348

__3. Using the post caption words as well as image labels as the independent variables__

In [229]:
df2 = pd.DataFrame(tfidf_matrix.toarray())

In [231]:
combination =  pd.concat([df1, df2], axis=1, sort=False)

In [232]:
lr3 = LogisticRegression()
lr3.fit(combination, normalized_data.iloc[:,-1])
pred3 = lr3.predict(combination)
matrix3 = confusion_matrix(normalized_data.iloc[:,-1], pred3)
matrix3

array([[360,  30],
       [ 36, 368]])

In [233]:
confusion_matrix_chart3 = pd.DataFrame(matrix3, columns=["Actual: True", "Actual: False"],  index=["Predicted: True", "Predicted: False"])
confusion_matrix_chart3

Actual: True  Actual: False
Predicted: True            360             30
Predicted: False            36            368

In [234]:
Accuracy3 = (360+368)/(360+30+36+368)
Accuracy3

0.9168765743073047

__Therefore, we will get a higher accuracy when combining the image labels and post captions and using them as independent variables to predict the dependent variable Engagement (binary). Also, the accuracy is higher when only using image labels as independent variables than only using post captions. __